[package]
name = "tetris"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.0"
ratatui = "0.29.0"
color-eyre ="0.6.3"
crossterm = "0.29.0"
rand = { version = "0.9.1", features = [] }
